### ISSUE TITLE
`AttenderState` POST 요청 시 500이 반환되는 문제

### ISSUE THREAD

**Issue by yy0867** [FirstianB101/pullgo-server#132]
`AttenderState`의 POST에서 요구하는 필드를 모두 채운 후
요청을 보내면 500 Internal Server Error가 반환됨.

### 서버 로그
![image](https://user-images.githubusercontent.com/27603734/142377288-0ddbaed4-75e4-489f-a2b0-64bb6c7096a2.png)

### Postman으로 요청 보냈을 때 (해당 `attenderId`와 `examId`는 유효)
![image](https://user-images.githubusercontent.com/27603734/142377445-d6d2ed5b-362e-4b86-a9ee-a1b67715fc2b.png)

**Comment by tellang** [comment]
DB에서 해당 문제되는 submitted 컬럼 삭제했음

**Comment by yy0867** [comment]
굿
